### ISSUE TITLE
Giiker features

### ISSUE THREAD

**Issue by tussosedan** [cs0x7f/cstimer#36] opened 2018-12-09 21:28 UTC
Giiker is working great in the new version!
A few feature requests:
1. As a Roux user, slice moves are very important -- would it be possible to add slice moves recognition? Someone on reddit said that a threshold of 30 ms is working well to differentiate between a slice move and simultaneous moves.
1. Would it be possible to save the reconstruction of the solve, maybe even with a link to open it in alg.cubing.net directly?
1. The automatic splits are great, could we get (in addition to the reconstruction per step) additional statistics of tps and pauses per step?

**Comment by cs0x7f** [comment] 2018-12-12 15:41
For the second suggestion, I added a simple reconstruction (a url to alg.cubing.net) yesterday https://github.com/cs0x7f/cstimer/commit/d7af16891596164dfbda10de213c89405355418c.
For a conventional solves, there is few data relatived. While for solves generated by Giiker cube or virtual cube, there are too many data to be analyzed. I have not found an available and convenient way to store, display, analyze, verify and export these data.

**Comment by tussosedan** [comment] 2018-12-12 15:44
Maybe hakatashi's work on this subject can be helpful?

https://github.com/hakatashi/smart-cube-timer

**Comment by cs0x7f** [comment] 2018-12-12 16:08
It's much more difficult for cstimer to implement equivalent function as hakatashi did, since we are going to add deep support of giiker cube.
The simplest way to support giiker cube is to treat it as another inputTimer. That's how cstimer is working with giiker cube now. But if we want to do more, it becomes extremely difficult.
For example, for tps data of stages of CFOP, it will be easy to just show them for each solve. But it is much harder to do any statistics on tps data. Similarly for oll/pll cases counting as hakatashi did. All of these functions can be implemented no doubt, but will be processed as an independent module in the tool panel or a popup dialog, like another program embedded into cstimer.

**Comment by HoshiYamazaki** [comment] 2018-12-24 22:30
Can I ask something? I have first version of Giiker and moves can just be "missed" which lead to not solved cube (not stopped timer) while solving it. Also virtual cube is not always showing when connecting to giiker - probably because it was paired before.

I bought V2 version, we will see if problems remains.

**Comment by cs0x7f** [comment] 2018-12-25 04:51
According to my test, moves are not missed but reordered, e.g. R U -> U R. That's how cstimer trying to correct errors.
It seems the v2 solves this problem, at least I cannot reproduce the same problem on the v2 cube.

**Comment by HoshiYamazaki** [comment] 2018-12-25 09:38
How to show virtual cube if is not visible then?

**Comment by HoshiYamazaki** [comment] 2018-12-25 09:41
Also, how to stop timer?

**Comment by cs0x7f** [comment] 2019-04-06 07:16
After the latest commit, the raw reconstruction of each solve generated by giiker cube or virtual cube is stored in the 5th entry without data loss. Then, each solve is stored as
`[[penalty, phaseN end time, phaseN-1 end time, ..., phase1 end time], scramble, comment, timestamp of start, extension]`
For giiker solves,
`extension = [raw_move_string_with_timestamp, number of phaseN cumulative moves, number of phaseN-1 cumulative moves, ..., phase1 moves]`
where move count is calculated after slice-move detection and adjust move merging.
raw_move_string_with_timestamp is something like
R@0 U@100 R'@200 R'@250 ...
where the number denotes the timestamp (in millisecond) of each moves.

Then, although many statistics is not available right now , we are able to support these statistics in the future or by some other third-party analyzers.

For convenience, I add a link in the time confirmation dialog when extension information is available.

**Comment by pajinko** [comment] 2019-05-31 11:51
Hello I have a new i3S Giiker cube - when I select Giiker as input the bluetooth search window opens in windows, the cube is found, but when I select it and choose to pair, the window is closed and nothing is happening.

which is still great compared to hakatashis site, where the cube is not found at all, but we could do better ;)

**Comment by cs0x7f** [comment] 2019-06-03 15:12
> 
> 
> Hello I have a new i3S Giiker cube - when I select Giiker as input the bluetooth search window opens in windows, the cube is found, but when I select it and choose to pair, the window is closed and nothing is happening.
> 
> which is still great compared to hakatashis site, where the cube is not found at all, but we could do better ;)

You can open tools with 'Giiker' function to check whether the cube is connected. 
If not, you can then press F12 to open browser console and check whether there is any error report logged.

**Comment by pajinko** [comment] 2019-06-04 04:54
> 
> 
> > Hello I have a new i3S Giiker cube - when I select Giiker as input the bluetooth search window opens in windows, the cube is found, but when I select it and choose to pair, the window is closed and nothing is happening.
> > which is still great compared to hakatashis site, where the cube is not found at all, but we could do better ;)
> 
> You can open tools with 'Giiker' function to check whether the cube is connected.
> If not, you can then press F12 to open browser console and check whether there is any error report logged.

Hello, I wanted to try your suggestions but this time the cube connected within a second and all is working fine.. So we can close this topic with the assumption it was a temporary issue on my side. Thank  you for your time anyways. 

However I noticed that if I choose to calculate splits for Roux in the menu, the 3rd split is not measuring the CMLL part only. It should stop counting when all upper corners are oriented, but it continues to count until the whole last layer is oriented which is not necessary in Roux. That should be part of the LSE - 4th step.

**Comment by cs0x7f** [comment] 2019-06-05 14:08
> It should stop counting when all upper corners are oriented, but it continues to count until the whole last layer is oriented which is not necessary in Roux.

In current implementation, 3rd split will stop counting when all 4 corners of last layer are solved (both positions and orientations).
It seems that some of roux players might leave 4 corners a U/U2/U' turn from solved, which might be recognized as CMLL unsolved right now. In the next version (available at /new/ ), these cases will be recognized as CMLL solved.

**Comment by pajinko** [comment] 2019-06-05 15:42
> 
> 
> > It should stop counting when all upper corners are oriented, but it continues to count until the whole last layer is oriented which is not necessary in Roux.
> 
> In current implementation, 3rd split will stop counting when all 4 corners of last layer are solved (both positions and orientations).
> It seems that some of roux players might leave 4 corners a U/U2/U' turn from solved, which might be recognized as CMLL unsolved right now. In the next version (available at /new/ ), these cases will be recognized as CMLL solved.

Yes - that is exactly the case - in Roux it is not necessary to have the corners positioned correctly, only oriented correctly... positioning them would be additional move that cost time and bring no value as they will be offset from their position in the LSE phase anyway. 

Thank you for the upcoming fix. appreciate your timely support and work!

**Closed** 2023-03-18 12:28 UTC
