### ISSUE TITLE
For smart cube solving in the case of a PLL skip, it fails to correctly recognize the OLL case

### ISSUE THREAD

**Issue by hujunkui** [cs0x7f/cstimer#333] opened 2023-12-14 05:56 UTC
Here's an example:
Scramble: F R' F' R U R U' R'
Solution: R U R' U' R' F R F'
In reality, the entire solution is broken down as follows:
R U R' U' R' F R // OLL
F' // PLL
However, the facelets of OLL are obtained by reversing the solution of OLL. In this case, the OLL solution does not result in facelets in the OLL state.

**Comment by afedotov** [comment] 2023-12-14 18:06
This is known and controversial issue. Duplicate of #263.

**Closed** 2023-12-15 02:06 UTC
